apiVersion: 1

datasources:
  - name: codex-sqlite
    uid: codex-sqlite
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    jsonData:
      path: /sqlite/codex.db
    editable: false